### ISSUE TITLE
Update child records: Status + Status Reason

### ISSUE THREAD

**Issue by GoSoli** [demianrasko/Dynamics-365-Workflow-Tools#54]
We use CRM on premise 8.2.2 and the Workflow Tools 1.0.49.0 (also tested before with 1.0.40.0).

I made a workflow which shall close all task regarding the quote when the quote is closed.
But the closing step brings an error independant if in foreground or background.

The steps and the detail of the attachment step are in the following screenshot.
![image](https://user-images.githubusercontent.com/36201081/35959073-40aba1a0-0ca4-11e8-936f-df65f8ac5da8.png)

It is clear that changing the status is not a usual update and I don't know if it is foreseen in the plugin. Especially I don't know if I must update StateCode and StatusCode and if both, in which order.
I tried some ways both nothing worked.

The error in the background task is:
"Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.UpdateChildRecords]
[msdyncrmWorkflowTools (1.0.49.0): Update Child Records]
Load CRM Service from context --- OK
ObjectTypeCode=1084--ParentId=20334e76-6dfb-e711-80db-005056a73cf9
RelationshipName=Quote_Tasks--_ParentFieldNameToUpdate=
_ValueToSet=6--_ChildFieldNameToUpdate=StatusCode

Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: Could not find attribute
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)"

What I also don't understand: In the background I always get the task 2 or 3 times.

Can you please tell me if my way should work or what I shall change in my definition. Thanks!

**Comment by demianrasko** [comment]
Hi GoSoli, 
I just found a bug on this point, and I just fixed.
But there is another thing on this point, when I fix the issue with the status code and try to execute the same thing you tried, I get this error: "6 is not a valid status code for state code TaskState.Open on task with Id b6d9bb78-5f0f-e811-811e-5065f38a1b01". When you change the statuscode you must to execute the change status or change the statecode too.
Right now, this feature didn't change it to support changing status on this action.

thanks

**Comment by GoSoli** [comment]
Hi Demian,
thanks for the fast answer.
I installed 1.0.50.0 but still have the error "Could not find attribute" and not your mentioned error. I also tried it with changing Statuscode + Statecode with same effect. I am not sure how to unterstand your answer if that could work or not.
And what still is: I get more than one workflow instances running (when in background).
![image](https://user-images.githubusercontent.com/36201081/36137594-424ac96e-1096-11e8-81ef-b1436717dbd0.png)
Can you clarify this, please.
I have some other requirements, too, where I should update the child records. So this would be a very nice feature for me.
